<?php
/**
 * OVH SMS gateway (https://www.ovhtelecom.fr/sms/).
 *
 * Uses the OVH API v1.0 with signed requests (AK + AS + CK).
 * Endpoint: POST /sms/{serviceName}/jobs
 *
 * Auth is a SHA1 signature of: "AS+CK+METHOD+URL+BODY+TIMESTAMP".
 *
 * DLR: OVH sends a callback with bstatus, statusDetails, datas, etc.
 * We identify the message by the ID OVH returned on send.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

class SRFA_Gateway_OVH implements SRFA_Gateway_Interface {

    const API_BASE = 'https://eu.api.ovh.com/1.0';

    public function get_id() { return 'ovh'; }

    public function get_label() {
        return __( 'OVH SMS', 'sms-reminder-for-amelia' );
    }

    public function get_description() {
        return __( 'European SMS provider by OVHcloud — good EU pricing, data hosted in Europe.', 'sms-reminder-for-amelia' );
    }

    public function get_fields() {
        return [
            [
                'key'         => 'service_name',
                'type'        => 'text',
                'label'       => __( 'Service name', 'sms-reminder-for-amelia' ),
                'description' => __( 'Your OVH SMS account identifier (e.g. sms-xx12345-1). OVH Manager → SMS → General info.', 'sms-reminder-for-amelia' ),
                'default'     => '',
                'placeholder' => 'sms-xx12345-1',
                'sanitize'    => 'sanitize_text_field',
            ],
            [
                'key'         => 'app_key',
                'type'        => 'text',
                'label'       => __( 'Application Key (AK)', 'sms-reminder-for-amelia' ),
                'description' => __( 'Create at eu.api.ovh.com/createApp.', 'sms-reminder-for-amelia' ),
                'default'     => '',
                'placeholder' => '',
                'sanitize'    => 'sanitize_text_field',
            ],
            [
                'key'         => 'app_secret',
                'type'        => 'password',
                'label'       => __( 'Application Secret (AS)', 'sms-reminder-for-amelia' ),
                'description' => __( 'The secret generated alongside the Application Key.', 'sms-reminder-for-amelia' ),
                'default'     => '',
                'placeholder' => '',
                'sanitize'    => 'sanitize_text_field',
            ],
            [
                'key'         => 'consumer_key',
                'type'        => 'password',
                'label'       => __( 'Consumer Key (CK)', 'sms-reminder-for-amelia' ),
                'description' => __( 'Generated by requesting a credential token with GET /sms/* permissions. See the OVH API documentation.', 'sms-reminder-for-amelia' ),
                'default'     => '',
                'placeholder' => '',
                'sanitize'    => 'sanitize_text_field',
            ],
            [
                'key'         => 'sender',
                'type'        => 'text',
                'label'       => __( 'Sender', 'sms-reminder-for-amelia' ),
                'description' => __( 'Registered sender name (must be pre-approved in OVH Manager → SMS → Senders).', 'sms-reminder-for-amelia' ),
                'default'     => '',
                'placeholder' => 'Reminder',
                'maxlength'   => 11,
                'sanitize'    => 'sanitize_text_field',
            ],
            [
                'key'         => 'no_stop_clause',
                'type'        => 'checkbox',
                'label'       => __( 'Suppress STOP clause', 'sms-reminder-for-amelia' ),
                'description' => __( 'Disable the legal "STOP" clause appended to marketing SMS. Only enable for transactional messages (appointment reminders qualify in most jurisdictions).', 'sms-reminder-for-amelia' ),
                'default'     => true,
            ],
        ];
    }

    public function send( $phone, $message, $settings ) {
        $service = trim( $settings['service_name'] ?? '' );
        $ak      = trim( $settings['app_key']      ?? '' );
        $as      = trim( $settings['app_secret']   ?? '' );
        $ck      = trim( $settings['consumer_key'] ?? '' );
        $sender  = trim( $settings['sender']       ?? '' );

        if ( $service === '' || $ak === '' || $as === '' || $ck === '' || $sender === '' ) {
            return [
                'success'    => false,
                'message_id' => null,
                'error'      => __( 'OVH SMS: one or more credentials are missing (service, AK, AS, CK, sender).', 'sms-reminder-for-amelia' ),
            ];
        }

        $url = self::API_BASE . '/sms/' . rawurlencode( $service ) . '/jobs';

        $body_data = [
            'charset'         => 'UTF-8',
            'coding'          => '8bit', // 8bit lets us use accents; 7bit is cheaper but ASCII only
            'message'         => $message,
            'receivers'       => [ $phone ],
            'sender'          => $sender,
            'senderForResponse' => false,
            'noStopClause'    => ! empty( $settings['no_stop_clause'] ),
            'priority'        => 'high',
        ];
        $body_json = wp_json_encode( $body_data );

        // OVH signed request
        $timestamp = $this->fetch_server_time();
        if ( $timestamp === null ) {
            return [
                'success'    => false,
                'message_id' => null,
                'error'      => __( 'OVH SMS: unable to fetch API server time.', 'sms-reminder-for-amelia' ),
            ];
        }

        $to_sign   = $as . '+' . $ck . '+POST+' . $url . '+' . $body_json . '+' . $timestamp;
        $signature = '$1$' . sha1( $to_sign );

        $response = wp_remote_post( $url, [
            'timeout'     => 20,
            'httpversion' => '1.1',
            'headers'     => [
                'X-Ovh-Application' => $ak,
                'X-Ovh-Consumer'    => $ck,
                'X-Ovh-Timestamp'   => $timestamp,
                'X-Ovh-Signature'   => $signature,
                'Content-Type'      => 'application/json;charset=utf-8',
            ],
            'body'        => $body_json,
        ] );

        if ( is_wp_error( $response ) ) {
            return [
                'success'    => false,
                'message_id' => null,
                'error'      => __( 'Network error:', 'sms-reminder-for-amelia' ) . ' ' . $response->get_error_message(),
            ];
        }

        $http_code = wp_remote_retrieve_response_code( $response );
        $data      = json_decode( wp_remote_retrieve_body( $response ), true );

        // Success: OVH returns 200 with ids (array) and validReceivers (array) + totalCreditsRemoved.
        if ( $http_code === 200 && ! empty( $data['ids'] ) && is_array( $data['ids'] ) ) {
            return [
                'success'    => true,
                'message_id' => (string) $data['ids'][0],
                'error'      => null,
            ];
        }

        $msg = isset( $data['message'] ) ? $data['message'] : __( 'Unknown error', 'sms-reminder-for-amelia' );
        return [
            'success'    => false,
            'message_id' => null,
            'error'      => sprintf( 'OVH: %s (HTTP %s)', $msg, $http_code ),
        ];
    }

    public function handle_dlr( WP_REST_Request $request ) {
        // OVH can POST JSON or x-www-form-urlencoded depending on configuration.
        $body = $request->get_json_params();
        if ( empty( $body ) ) {
            $body = $request->get_params();
        }

        $message_id = $body['id'] ?? ( $body['messageId'] ?? null );
        $bstatus    = $body['bstatus'] ?? ( $body['status'] ?? null );

        if ( empty( $message_id ) || $bstatus === null ) {
            return null;
        }

        // OVH bstatus codes: -1 pending, 0/1/2 delivered (varies), >= 4 failed.
        $code = (int) $bstatus;
        if ( $code === -1 ) {
            $internal = 'pending';
        } elseif ( $code >= 0 && $code <= 2 ) {
            $internal = 'delivered';
        } else {
            $internal = 'failed';
        }

        return [
            'message_id' => sanitize_text_field( (string) $message_id ),
            'status'     => $internal,
        ];
    }

    /**
     * OVH signed requests require a timestamp within a few seconds of OVH server time.
     * Fetching /auth/time avoids clock drift issues.
     *
     * @return int|null Unix timestamp or null on failure.
     */
    protected function fetch_server_time() {
        $response = wp_remote_get( self::API_BASE . '/auth/time', [ 'timeout' => 10 ] );
        if ( is_wp_error( $response ) ) { return null; }
        $ts = trim( wp_remote_retrieve_body( $response ) );
        if ( ! ctype_digit( $ts ) ) { return null; }
        return (int) $ts;
    }
}
